name: CI

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LHCI_UPLOAD___TOKEN: ${{ secrets.LHCI_UPLOAD__TOKEN }}
  LHCI_GITHUB_APP_TOKEN: $ {{ secrets.LHCI_GITHUB_APP_TOKEN }}
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: "actions/setup-node@v3"
        with:
          node-version-file: ".nvmrc"
          # cache: "pnpm"
          # cache-dependency-path: "**/pnpm-lock.yaml"
      - run: corepack enable
      - uses: pnpm/action-setup@v2
        with:
          version: 7.22.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: pnpm install, build
        run: |
          pnpm install
          pnpm build
      - name: run Lighthouse CI
        run: pnpm lhci autorun
      - name: Run Lighthouse on urls and upload data to private lhci server
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: "https://example.com/"
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_UPLOAD__TOKEN }}
